services:
  # tor 用
  tor:
    build:
      context: .
  
  web: # ページ公開用
    image: httpd:2.4
    volumes:
      - type: bind
        source: ./web/
        target: /usr/local/apache2/htdocs/
    ports:
      - "8888:80" # 8888 で一般ネットワークでの確認用